url: http://www.forwardingplane.net
name: The Forwarding Plane
description: >
  A wealth of run on sentences, misspelled
  words, and grammatical errors related to
  Routing, Switching, Security,
  Strategy....The lunatic fringe.
